## Get all tasks
GET http://localhost:8080/api/v1/todolist?size=2&page=2&sort=title

### Get task by id
GET http://localhost:8080/api/v1/todolist/1

### Create
POST http://localhost:8080/api/v1/todolist
Content-Type: application/json

  {
    "title": "bTest task1"
  }

### Update task
PUT http://localhost:8080/api/v1/todolist/1
Content-Type: application/json

{
  "title": "Test edited"
}

### Delete task
DELETE http://localhost:8080/api/v1/todolist/2